{{- if .Values.configs.infra }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "DXLchart.fullname" . }}-infra
  labels:
    {{- include "DXLchart.governanceLabels" . | nindent 4 }}
  annotations:
    {{- include "DXLchart.governanceAnnotations" . | nindent 4 }}
data:
  {{- .Values.configs.infra | toYaml | nindent 2 }}
{{- end }}
