{{- if .Values.fluentbit.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-fluentbit-config
  labels:
    {{- include "DXLchart.governanceLabels" . | nindent 4 }}
  annotations:
    {{- include "DXLchart.governanceAnnotations" . | nindent 4 }}
data:
  {{ .Values.fluentbit.configFile | default "fluent-bit.conf" }}: |-
    [SERVICE]
      Flush        5
      Daemon       Off
      Log_Level    info

    [INPUT]
      Name   tail
      Path   {{ .Values.fluentbit.logsFolder | default "/logs" }}/application.log
      Refresh_Interval 10
      Mem_Buf_Limit 20MB
      Buffer_Max_Size 10MB
      Buffer_Chunk_Size 500k

    [OUTPUT]
      Name kafka
      Match  *
      Brokers {{ .Values.fluentbit.brokers | default "kafka:9092" }}
      Topics {{ .Values.fluentbit.topic | default "test" }}
      Retry_Limit    false
      rdkafka.log.connection.close false
      rdkafka.queue.buffering.max.kbytes 10240
      rdkafka.request.required.acks 1
      rdkafka.ssl.endpoint.identification.algorithm https
      rdkafka.security.protocol sasl_ssl
      rdkafka.sasl.mechanism SCRAM-SHA-512
      rdkafka.sasl.username 48but-dxl-nonprod-cz
      rdkafka.sasl.password ${kafkapassword}
      rdkafka.bootstrap.servers {{ .Values.fluentbit.brokers | default "kafka:9092" }}
      rdkafka.enable.ssl.certificate.verification false
{{- end }}
