apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "DXLchart.fullname" . }}
  labels:
  {{- include "DXLchart.labels" . | nindent 4 }}
  annotations:
  {{- include "DXLchart.governanceAnnotations" . | nindent 4 }}
spec:
  podSelector:
    matchLabels: {{- include "DXLchart.selectorLabels" . | nindent 6 }}
  ingress:
    - from:
      - podSelector: {}
      ports:
        - protocol: TCP
          port: 8080
    - from:
      - podSelector:
          matchLabels:
            app.kubernetes.io/name: instana-agent
    {{- range .Values.network.ingress }}
    - from:
        - podSelector:
            matchLabels:
              name: {{ .name | quote }}
      ports:
        - protocol: {{ .protocol | default "TCP" }}
          port: {{ .port }}
    {{- end }}
  egress:
    - to:
      - podSelector:
          matchLabels:
            app.kubernetes.io/name: instana-agent
    - to:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: 8080
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 443
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 9093
        - protocol: TCP
          port: 6096
        - protocol: TCP
          port: 7096
        - protocol: TCP
          port: 8096
        - protocol: TCP
          port: 27017
        - protocol: TCP
          port: 42699
        - protocol: TCP
          port: 443
    {{- range .Values.network.egress }}
    - to:
      - podSelector:
          matchLabels:
            app.kubernetes.io/name: {{ .podName | quote }}
            app.kubernetes.io/instance: {{ .podInstance | quote }}
      ports:
        - protocol: {{ .protocol | default "TCP" }}
          port: {{ .port }}
    {{- end }}
  policyTypes:
    - Ingress
    - Egress
