{{- if .Values.secrets.passwords -}}
{{- $fullname := print (include "DXLchart.fullname" .) (.Values.secrets.passwordsNameSuffix | default "-passwords") -}}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace $fullname) -}}
{{- $data := .Values.secrets.passwordsLookup | ternary ($secret.data | default dict) dict -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullname }}
  labels:
    {{- include "DXLchart.governanceLabels" . | nindent 4 }}
  annotations:
    {{- include "DXLchart.governanceAnnotations" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $value := .Values.secrets.passwords }}
  {{ $key }}: {{ if hasKey $data $key }}{{ get $data $key }}{{ else }}{{ $value | b64enc }}{{ end }}
{{- end }}
{{- end }}
