{{- if .Values.secrets.files -}}
{{- $fullname := print (include "DXLchart.fullname" .) "-files" -}}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace $fullname) -}}
{{- $data := ($secret.data | default dict) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullname }}
  labels:
    {{- include "DXLchart.governanceLabels" . | nindent 4 }}
  annotations:
    {{- include "DXLchart.governanceAnnotations" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $value := .Values.secrets.files }}
  {{ $key }}: {{ if hasKey $data $key }}{{ get $data $key }}{{ else }}{{ $value | b64enc }}{{ end }}
{{- end }}
{{- end }}
