{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "DXLchart.serviceAccountName" . }}
  labels:
  {{- include "DXLchart.labels" . | nindent 4 }}
  annotations:
  {{- include "DXLchart.governanceAnnotations" . | nindent 4 }}
{{- end }}
