apiVersion: v1
kind: Service
metadata:
  name: {{ include "DXLchart.fullname" . }}
  labels:
    {{- include "DXLchart.labels" . | nindent 4 }}
  annotations:
    {{- include "DXLchart.governanceAnnotations" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port | default 8080 }}
      targetPort: {{ .Values.service.targetPort | default 8080 }}
      protocol: TCP
      name: http
  selector:
    {{- include "DXLchart.selectorLabels" . | nindent 4 }}
