{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ChartName.serviceAccountName" . }}
  labels:
  {{- include "ChartName.labels" . | nindent 4 }}
  annotations:
  {{- include "ChartName.governanceAnnotations" . | nindent 4 }}
{{- end }}
